# Copyright (c) 2023 Z5Labs and Contributors
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

FROM scratch
EXPOSE 9080
COPY simple_grpc /
ENTRYPOINT ["/simple_grpc"]