# Copyright (c) 2023 Z5Labs and Contributors
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

FROM scratch
EXPOSE 8080
COPY simple_http /
ENTRYPOINT ["/simple_http"]